version: "2"

services:
  db:
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: changeme
    restart: always
    image: postgres:14.1
    expose:
      - "5432"
  server_wsgi:
    build:
      context: .
      dockerfile: ./server_wsgi.Dockerfile
    environment:
      SECRET_KEY: changeme
      DEBUG: "true"
      ALLOWED_HOSTS: localhost,server-wsgi.benchmark-wagtail-demo.orb.local
      DATABASE_URL: postgres://app_user:changeme@db/app_db
      DJANGO_SETTINGS_MODULE: mysite.settings.production
      SECURE_HSTS_SECONDS: 0
      SECURE_SSL_REDIRECT: false
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "8000:8000"
  server_next:
    build:
      context: .
      dockerfile: ./server_next.Dockerfile
    environment:
      NEXT_OUTPUT: standalone
    ports:
      - "8002:3000"
  static_wsgi:
    build:
      context: .
      dockerfile: ./static_wsgi.Dockerfile
    ports:
      - "8003:80"
  static_next:
    build:
      context: .
      dockerfile: ./static_next.Dockerfile
    ports:
      - "8004:80"
